# Video parameters
videoFolder: "./videos"
videoFilename: "test2_frontcam.mp4"
frameRate: 150
recTimeInSec: 20

# Camera parameters
cameraSelection: [1]                  # If multiple cameras are connected
cameraMake: "basler"
cameraSettings: "./configs/daA1920-160um_40281170.pfs"
pixelFormatInput: "gray"
pixelFormatOutput: "rgb0"
frameWidth: 1920
frameHeight: 1200

# Compression parameters
gpuID: 0                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
ffmpegLogLevel: "quiet"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda


# Display parameters
chunkLengthInSec: 5
displayFrameRate: 10

# Trigger parameters
startArduino: True
serialPort: "COM5"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [1]
