# This beginner-level config uses the CPU (gpuID: -1) 
# to compress RGB video
# using ffmpeg's X264 codec

# Recording parameters
videoFolder: "./test"
videoFilename: "singlecam1.mp4"
frameRate: 150
recTimeInSec: 30

# Camera parameters
numCams: 1
cameraMake: "basler"
cameraSettings: "./configs/daA1920-160um_40281170.pfs"
frameWidth: 1920  
frameHeight: 1200

# Compression parameters
gpuID: -1
pixelFormatInput: "gray"
pixelFormatOutput: "rgb0"
quality: 17
ffmpegLogLevel: "warning"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
displayFrameRate: 10

# Trigger parameters
cameraTrigger: "software"
