# This moderate-level config uses the GPU 
# to compress 3 RGB streams in parallel

# Video parameters
videoFolder: "./videosgpuhb3cam"
videoFilename: "test_hb_gpu_3cam.mp4"
frameRate: 150
recTimeInSec: 120

# Camera parameters
numCams: 3
cameraSelection: [0,1,2]
cameraNames: ["Camera1","Camera2","Camera3"]
cameraMake: "basler"
cameraSettings: "./configs/daA1920-160um_40281170.pfs"
pixelFormatInput: "gray" 
pixelFormatOutput: "rgb0"
frameWidth: 1920
frameHeight: 1200

# Compression parameters

gpuID: 0                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h265"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
ffmpegLogLevel: "warning"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda


# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10

# Trigger Parameters
startArduino: True
serialPort: "COM5"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [0,1,2]
